cmake_policy(SET CMP0048 NEW)
cmake_minimum_required(VERSION 3.13.0)


set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/cmsis-dsp.cmake)

project(CMSIS-DSP)

option(LAXVECTORCONVERSIONS OFF)
set(LOOPUNROLL ON CACHE BOOL "")
set(DISABLEFLOAT16 ON CACHE BOOL "")
set(LAXVECTORCONVERSIONS OFF CACHE BOOL "")

set(CMSISCORE ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../cmsis/CMSIS_6/CMSIS/Core)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../../../cmsis/CMSIS-DSP ${PROJECT_BINARY_DIR}/cmsis/CMSIS-DSP)

install (
    TARGETS CMSISDSP
    DESTINATION ${PROJECT_SOURCE_DIR}/lib
)
